
version: 2

models:
  - name: t_agg_daily_btc_trade_block_data_p
    description: "Exposition table of the daily aggregated data for Bitcoin trade and blockchain blocks data"
    columns:
      - name: pair
        description: "Trading pair"
      - name: date
        description: "Date of the data"
      - name: avg_trade_price
        description: "Average price of the asset in USD"
      - name: min_trade_price
        description: "Minimum price of the asset in USD"
      - name: max_trade_price
        description: "Maximum price of the asset in USD"
      - name: trade_volume
        description: "Total volume of the asset traded"
      - name: trades_count
        description: "Number of trades"
      - name: buy_operations_count
        description: "Number of buy operations"
      - name: sell_operations_count
        description: "Number of sell operations"
      - name: market_type_orders_count
        description: "Number of market type orders"
      - name: limit_type_orders_count
        description: "Number of limit type orders"
      - name: min_block_size
        description: "Minimum size of block data in bytes"
      - name: max_block_size 
        description: "Maximum size of block data in bytes"
      - name: avg_block_size
        description: "Average size of block data in bytes"
      - name: block_difficulty
        description: "Block difficulty"
      - name: min_block_transaction_count
        description: "Minimum number of transactions included in a block"
      - name: max_block_transaction_count
        description: "Maximum number of transactions included in a block"
      - name: avg_block_transaction_count
        description: "Average number of transactions included in a block"
      - name: trades
        description: "Nested field with all trades for the day"
      - name: trades.trade_id
        description: "Trade ID"
      - name: trades.price
        description: "Price of the asset in USD"
      - name: trades.volume
        description: "Volume of the asset traded"
      - name: trades.epoch_time
        description: "Timestamp of the trade in epoch format"
      - name: trades.timestamp_time
        description: "Timestamp of the trade in human readable format"
      - name: trades.operation_type
        description: "Type of operation (buy/sell)"
      - name: trades.order_type
        description: "Type of order (market/limit)"
      - name: trades.miscellanious
        description: "Miscellanious information"
      - name: blocks
        description: "Nested field with all blocks for the day"
      - name: blocks.hash
        description: "Hash of this block "
      - name: blocks.size
        description: "The size of block data in bytes"
      - name: blocks.stripped_size
        description: "The size of block data in bytes excluding witness data"
      - name: blocks.weight
        description: "Three times the base size plus the total size. https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki "
      - name: blocks.number
        description: "The number of the block"
      - name: blocks.version
        description: "Protocol version specified in block header"
      - name: blocks.merkle_root
        description: "The root node of a Merkle tree, where leaves are transaction hashes"
      - name: blocks.timestamp
        description: "Block creation timestamp specified in block header"
      - name: blocks.timestamp_month
        description: "Month of the block creation timestamp specified in block header"
      - name: blocks.nonce
        description: "Difficulty solution specified in block header"
      - name: blocks.bits
        description: "Difficulty threshold specified in block header"
      - name: blocks.coinbase_param
        description: "Data specified in the coinbase transaction of this block"
      - name: blocks.transaction_count
        description: "Number of transactions included in this block"


