version: 2

sources:
  - name: dv_btc_data_bronze
    tables:
      - name: t_xbtusd_trade_data_b
        description: "Raw data from Kraken"
        external:
          location: 'gs://kraken_data_bucket_de_project/XBTUSD/XBTUSD-*.parquet.gzip'
          options:
            format: PARQUET
  - name: bigquery-public-data
    database: bigquery-public-data
    schema: crypto_bitcoin
    tables:
      - name: blocks