version: 2

sources:
  - name: dv_btc_data_bronze
    tables:
      - name: t_xbtusd_trade_data_b
        description: "Raw data from Kraken Trades API"
        external:
          location: 'gs://kraken_data_bucket_de_project/XBTUSD/XBTUSD-*.parquet.gzip'
          options:
            format: PARQUET
        columns:
          - name: price
            description: "Price of the asset in USD"
          - name: volume
            description: "Volume of the asset traded"
          - name: epoch
            description: "Timestamp of the trade in epoch format"
          - name: timestamp_time
            description: "Timestamp of the trade in human readable format"
          - name: operation_type
            description: "Type of operation (buy/sell)"
          - name: order_type
            description: "Type of order (market/limit)"
          - name: miscellanious
            description: "Miscellanious information"
          - name: trade_id
            description: "Trade ID"
  - name: bigquery-public-data
    database: bigquery-public-data
    schema: crypto_bitcoin
    tables:
      - name: blocks